### ISSUE TITLE
How to list custom datatypes in group

### ISSUE THREAD

**Issue by ashutosh840** [Dimibe/grouped_list#45]
`
```
class record{

  String Name;
  int DayofBirth;

  record(String Name, int DayofBirth){
    Name=this.Name;
    DayofBirth=this.DayofBirth;
  }

}
```

`
`Now I want the following list `
`
```
 var lists=[

    record("Ashu",DateTime.thursday),
    record("Aniket",DateTime.monday),
    record("Eishu",DateTime.saturday),
    record("Keshav",DateTime.thursday),


  ];
```

`
Into the grouped list according to **DayofBirth**  

This is my GroupListView
`
```
GroupedListView<dynamic,record>(
                elements: lists,
                groupBy: (element)=>element.DayofBirth,
                groupSeparatorBuilder: _buildSperator,
                itemBuilder: (context, element) => Text(element.Name),
                order: GroupedListOrder.ASC,
              ),
Widget _buildSperator(dynamic groupByValue){
  return Text(groupByValue);

}
```

`

**Comment by Dimibe** [comment]
@ashutosh840 What exactly is the problem? 
Can you tell me how the list looks with your implementation and what you would expect instead?

**Comment by ashutosh840** [comment]
It should be like this
```
**thursday**
Ashutosh
keshav
**monday**
Aniket
**thursday**
Eishu

```

**Comment by ashutosh840** [comment]
There would be no stars it is just to say that it is the header

**Comment by Dimibe** [comment]
@ashutosh840 okay I unterstand.
After a look at your code it should be displayd exactly like this.
How is it at the moment? Can you post a screenshot or any information to get the problem?

**Comment by ashutosh840** [comment]
It is showing some error. Please try it on your computer you will see it.

**Comment by Dimibe** [comment]
After rereading your code I notice some mistakes, that do not have anything do to with this plugin.
In your constructor you are not assigning the values to the class attributes but you assign class attributes to the variables. 

In case of this: 
```dart
 record(String Name, int DayofBirth){
    Name=this.Name;
    DayofBirth=this.DayofBirth;
  }
```

It need to be like this: 
```dart
 record(String Name, int DayofBirth){
    this.Name=Name;
    this.DayofBirth=DayofBirth;
  }
```

In dart you you can just write, it is the same as the above: 
```dart
record(this.Name, this.DayofBirth);
```
With this change your code should run as expected. 

Some  further recommendations which do not affect the execution of your code: 
Variables names should always be in camel case, so `name` instead of `Name` and `dayOfBirth` instead `DayofBirth`. 
Class names should always start with a capital letter, so `Record` instead of `record`. 

Here is a good articel from the offical website which might help you: 
https://dart.dev/guides/language/language-tour

**Comment by ashutosh840** [comment]
Sorry to say but error again popped out

```
I/flutter (13058): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (13058): The following NoSuchMethodError was thrown building GroupedListView<dynamic, int>(dirty, state:
I/flutter (13058): _GroupedListViewState<dynamic, int>#8e997):
I/flutter (13058): Class 'record' has no instance getter 'DayOfBirth'.
I/flutter (13058): Receiver: Instance of 'record'
I/flutter (13058): Tried calling: DayOfBirth
I/flutter (13058): 
I/flutter (13058): The relevant error-causing widget was:
I/flutter (13058):   GroupedListView<dynamic, int>
I/flutter (13058):   file:///D:/flutterProjects/moneymanager/groupedlist/lib/main.dart:35:20
I/flutter (13058): 
I/flutter (13058): When the exception was thrown, this was the stack:
I/flutter (13058): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
I/flutter (13058): #1      MyApp.build.<anonymous closure> (package:groupedlist/main.dart:37:43)
I/flutter (13058): #2      _GroupedListViewState._sortElements.<anonymous closure> (package:grouped_list/grouped_list.dart:173:27)
I/flutter (13058): #3      Sort._insertionSort (dart:_internal/sort.dart:71:36)
I/flutter (13058): #4      Sort._doSort (dart:_internal/sort.dart:60:7)
I/flutter (13058): #5      Sort.sort (dart:_internal/sort.dart:35:5)
I/flutter (13058): #6      ListMixin.sort (dart:collection/list.dart:341:10)
I/flutter (13058): #7      _GroupedListViewState._sortElements (package:grouped_list/grouped_list.dart:171:16)
I/flutter (13058): #8      _GroupedListViewState.build (package:grouped_list/grouped_list.dart:78:28)
I/flutter (13058): #9      StatefulElement.build (package:flutter/src/widgets/framework.dart:4619:28)
I/flutter (13058): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
I/flutter (13058): #11     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
I/flutter (13058): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
I/flutter (13058): #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
I/flutter (13058): #14     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4666:11)
I/flutter (13058): #15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
I/flutter (13058): ...     Normal element mounting (28 frames)
I/flutter (13058): #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
I/flutter (13058): #44     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5947:32)
I/flutter (13058): ...     Normal element mounting (185 frames)
I/flutter (13058): #229    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
I/flutter (13058): #230    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5947:32)
I/flutter (13058): ...     Normal element mounting (253 frames)
I/flutter (13058): #483    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
I/flutter (13058): #484    Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
I/flutter (13058): #485    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1148:16)
I/flutter (13058): #486    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1119:5)
I/flutter (13058): #487    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1061:17)
I/flutter (13058): #488    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2607:19)
I/flutter (13058): #489    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1060:13)
I/flutter (13058): #490    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:941:7)
I/flutter (13058): #491    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:922:7)
I/flutter (13058): (elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
I/flutter (13058): 
I/flutter (13058): ════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building GroupedListView<dynamic, int>(dirty, state: _GroupedListViewState<dynamic, int>#8e997):
Class 'record' has no instance getter 'DayOfBirth'.
Receiver: Instance of 'record'
Tried calling: DayOfBirth

The relevant error-causing widget was: 
  GroupedListView<dynamic, int> file:///D:/flutterProjects/moneymanager/groupedlist/lib/main.dart:35:20
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      MyApp.build.<anonymous closure> (package:groupedlist/main.dart:37:43)
#2      _GroupedListViewState._sortElements.<anonymous closure> (package:grouped_list/grouped_list.dart:173:27)
#3      Sort._insertionSort (dart:_internal/sort.dart:71:36)
#4      Sort._doSort (dart:_internal/sort.dart:60:7)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**the code is**

```
GroupedListView<dynamic,int>(
              elements: lists,
              groupBy: (element)=>element.DayOfBirth,
              groupSeparatorBuilder: _buildGroupSeparator,
              itemBuilder: (context, element) => Text(element.Name),
              order: GroupedListOrder.ASC,
            )
Widget _buildGroupSeparator(dynamic groupByValue){

  return Text(groupByValue);

}
```
```
class record{

  String Name;
  int DayofBirth;

  record(this.Name,this.DayofBirth);

}

````
